/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mypasswords7_gui_embeddedweb_LoginProfile */

#ifndef _Included_com_mypasswords7_gui_embeddedweb_LoginProfile
#define _Included_com_mypasswords7_gui_embeddedweb_LoginProfile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mypasswords7_gui_embeddedweb_LoginProfile
 * Method:    nativeGenToken
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mypasswords7_gui_embeddedweb_LoginProfile_nativeGenToken
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mypasswords7_gui_embeddedweb_LoginProfile
 * Method:    nativeCheckToken
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mypasswords7_gui_embeddedweb_LoginProfile_nativeCheckToken
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
